runtime! debian.vim


" Vundle Seetings Begining

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugin on GitHub repo
" -- Plugin 'tpope/vim-fugitive' --
Plugin 'scrooloose/nerdtree'
nmap <F5> :NERDTreeToggle<CR>
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_sep=' '
let g:airline#extensions#tabline#left_alt_sep='|'
let g:airline_theme='simple'
let g:airline#extensions#tabline#show_tabs=1
let g:airline#extensions#tabline#tab_nr_type=2
let g:airline#extensions#tabline#show_tab_nr=1
nmap \1 <Plug>AirlineSelectTab1
nmap \2 <Plug>AirlineSelectTab2
nmap \3 <Plug>AirlineSelectTab3
nmap \4 <Plug>AirlineSelectTab4
nmap \5 <Plug>AirlineSelectTab5
nmap \6 <Plug>AirlineSelectTab6
nmap \7 <Plug>AirlineSelectTab7
nmap \8 <Plug>AirlineSelectTab8
nmap \9 <Plug>AirlineSelectTab9
nmap \- <Plug>AirlineSelectPrevTab
nmap \+ <Plug>AirlineSelectNextTab
Plugin 'kien/ctrlp.vim'
let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
Plugin 'majutsushi/tagbar'
nmap <F8> :TagbarToggle<CR>

" Plugin from http://vim-scripts.org/vim/scripts.html
" -- Plugin 'L9' --

" Git plugin not hosted on GitHub
" -- Plugin 'git://git.wincent.com/command-t.git' --

" git repos on your local machine
" -- Plugin 'file:///home/gmarik/path/to/plugin' --

" The sparkup vim script is in a subdirectory of this repo called vim
" Pass the path to set the runtimepath properly
" -- Plugin 'rstacruz/sparkup', {'rtp': 'vim/'} --

" Install L9 and avoid a Naming conflict if you've already installed a different version somewhere else
" -- Plugin 'ascenator/L9', {'name': 'newL9'} --

"All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" to ignore plugin indent changes, instead use:
" filetype plugin on

" Brief help
" :PluginList          lists configured plugins
" :PluginInstall       installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo    searches for foo; append `!` to refresh local cache
" :PluginClean         confirms removal of unused plugins; append `!` to auto-approve reoval
"
" see :h vundle for more details or wiki for FAQ
" put your non-Plugin stuff after this line

" Vundle Seetings Ending


" 设置当前行高亮
set cursorline
" 个性化配置配色,cterm为原生vim设置样式
highlight CursorLine cterm=NONE ctermbg=black ctermfg=green guibg=NONE guifg=NONE
" 不使用代码折叠功能
set nofoldenable
" 不使用swapfile
set noswapfile
" 设置编码格式
set encoding=utf-8
" 语法高亮
syntax on
" 显示行号
set number
" 记录历史的行数
set history=1000
" 背景使用黑色
set background=dark
" 自动对齐
set autoindent
" 智能对齐
set smartindent
" tab键位用空格代替
set expandtab
" tab键位4个空格
set tabstop=4
" 当行之间交错时使用4个空格
set shiftwidth=4
" 将4个空格看待成tab键
set softtabstop=4
" 在右下角显示光标位置的状态行
set ruler
" 默认寻找匹配是高亮度显示的，关闭高亮显示
set nohls
" 查询时快速找到答案
set incsearch
" 设定编码类型，解决中文编码问题
let &termencoding=&encoding
set fileencodings=utf-8,gbk,ucs-bom,cp936
" 设置默认进行大小写不敏感查找
set ignorecase
" 如果有一个大写字母，则切换到大小写敏感查找
set smartcase
" 当光标一段时间保持不动了，就禁用搜索高亮
autocmd cursorhold * set nohlsearch
" 当输入查找命令时，再启用高亮
noremap n :set hlsearch<cr>n
noremap N :set hlsearch<cr>N
noremap / :set hlsearch<cr>/
noremap ? :set hlsearch<cr>?
noremap * *:set hlsearch<cr>

if has('mouse')
	set mouse-=a
endif

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
