#!/bin/bash

# php代码更新
function php_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cp -f .env.bak .env
        cd app/Containers/Project/Configs && cp -f project.php.bak project.php
    fi
    cd /home/$1 && php artisan migrate
    if [ $? -ne 0 ]; then
        composer install && php artisan migrate
    fi
    echo -e "----$1($2) update complete----\n"
}

php_update "ParallelForPhp_new" "180424"
php_update "php_02" "master"


# 会员中心
function member_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cd config/ && cp -f params.js.bak params.js && cp -f session.js.bak session.js && cp -f cache.js.bak cache.js
    fi
    echo -e "----$1($2) update complete----\n"
}

member_update "MemberCenterForSails" "master"
member_update "member_02" "master"


# 门户网站
function portal_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cd config/ && cp -f local.js.bak local.js && cp -f cache.js.bak cache.js && cp -f params.js.bak params.js
    fi
    echo -e "----$1($2) update complete----\n"
}

portal_update "ParallelPortalForSails" "master"
portal_update "portal_02" "master"


# api代码更新
function api_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cd config/ && cp -f connections.js.bak connections.js && cp -f local.js.bak local.js && cp -f sockets.js.bak sockets.js && cp -f cache.js.bak cache.js
    fi
    echo -e "----$1($2) update complete----\n"
}

api_update "ParallelApiForSails" "master"
api_update "api_02" "master"


# 打包环境更新
function package_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cp -f server.js.bak server.js
    fi
    echo -e "----$1($2) update complete----\n"
}

# package_update "ParallelConsultingPro" "master"  
# package_update "ParallelBackendPro" "master"
# package_update "ParallelParkPro" "master"
# package_update "ParallelExpertPro" "master"
# package_update "ParallelOwnerPro" "master"



# VUE环境更新
function vue_update() {
    cd /home/$1 && git pull origin $2
    if [ $? -ne 0 ]; then
        echo "!!!$1($2) pull failed, will change something and pull again!!!"
        git stash && git pull origin $2
        cp -f config/index.js.bak config/index.js
        cp -f src/conf/params.js.bak src/conf/params.js
    fi
    echo -e "----$1($2) update complete----\n"
}

# vue_update "ParallelConsultationForVue"  "27L0416"
vue_update "old_consultation" "27L0416"
# vue_update "owner_02" "20180413"
vue_update "new_back" "27LKnowledgeBase"
# vue_update "park_02" "dev"

