#!/bin/bash

cd /home/ParallelForPhp && git pull origin master
if [ $? -ne 0 ]; then
    echo "forphp pull failed, will change something and pull again"
    git stash && git pull origin master
    cp -f .env.bak .env
    cd /home/ParallelForPhp/app/Containers/Project/Configs && cp -f project.php.bak project.php
fi
cd /home/ParallelForPhp && php artisan migrate
if [ $? -ne 0 ]; then
    composer install && php artisan migrate
fi
echo -e "ForPhp update success\n"


cd /home/MemberCenterForSails && git pull
if [ $? -ne 0 ]; then
    echo "MemberCenter pull failed, will change something and pull again"
    git stash && git pull
    cd /home/MemberCenterForSails/config && cp -f params.js.bak params.js && cp -f session.js.bak session.js && cp -f cache.js.bak cache.js
fi
echo -e "MemberCenter pull success\n"

function consulting_update() {
    cd /home/ParallelConsultingPro && git pull origin dev
    if [ $? -ne 0 ]; then
        echo "Consulting pull failed, will change something and pull again"
        git stash && git pull origin dev
        cp -f server.js.bak server.js
    fi
    echo -e "ConsultingPro update success\n"
}

function consultation_update() {
    cd /home/ParallelConsultationForVue && git pull origin dev:dev
    if [ $? -ne 0 ]; then
        echo "Consultation pull failed, will change something and pull again"
        git stash && git pull origin dev:dev
        cp -f config/index.js.bak config/index.js
        cp -f src/conf/params.js.bak src/conf/params.js
    fi
    echo -e "Consultation update success\n"
}

consultation_update
consulting_update

cd /home/ParallelApiForSails && git pull
if [ $? -ne 0 ]; then
    echo "api pull failed, will change something and pull again"
    git stash && git pull
    cd /home/ParallelApiForSails/config && cp -f connections.js.bak connections.js && cp -f local.js.bak local.js && cp -f sockets.js.bak sockets.js && cp -f cache.js.bak cache.js
fi
echo -e "Api update success\n"
cd /home/ParallelBackendPro && git pull
if [ $? -ne 0 ]; then
    echo "pull failed, will change something and pull again"
    git stash && git pull
    cp -y server.js.bak server.js
fi
echo -e "BackendPro update success\n"
cd /home/ParallelPortalForSails && git pull
if [ $? -ne 0 ]; then
    echo "pull failed, will change something and pull again"
    git stash && git pull
    cd /home/ParallelPortalForSails/config && cp -f local.js.bak local.js && cp -f cache.js.bak cache.js && cp -f params.js.bak params.js
fi
echo -e "Portal update success\n"
cd /home/ParallelOwnerPro && git pull
if [ $? -ne 0 ]; then
    echo "pull failed, will change something and pull again"
    git stash && git pull
    cp -f server.js.bak server.js
fi
echo -e "OwnerPro update success\n"
cd /home/ParallelExpertPro && git pull
if [ $? -ne 0 ]; then
    echo "pull failed, will change something and pull again"
    git stash && git pull
    cp -f server.js.bak server.js
fi
echo -e "ExpertPro update success\n"
cd /home/ParallelParkPro && git pull
if [ $? -ne 0 ]; then
    echo "pull failed, will change something and pull again"
    git stash && git pull
    cp -f server.js.bak server.js
fi
echo -e "ParkPro update success\n"
