version: '2'

services:
    caddy:
        container_name: caddy
        image: abiosoft/caddy
        volumes:
            - "/etc/caddy/certs:/etc/caddycerts"
            - "/etc/caddy/Caddyfile:/etc/Caddyfile"
            - "/home:/home"
        ports:
            - 80:80
            - 443:443
        network_mode: "host"
        restart: always
        environment:
            CADDYPATH: /etc/caddycerts
